Add an inline Instructor Note warning about different flag behaviour
LibraryCarpentry/lc-shell pull request #284
Opened 2024-11-07 15:14 UTC by tobyhodges

The general Instructor Notes mention that

> grep -E on macOS X acts like grep -P on other platforms. On Windows and Linux, grep -E is halfway between grep -P and grep: it only does what grep can do, but uses Perl-compatible syntax to do it.

This pull request adds an inline Instructor Note to display this information next to the exercise where this confusion is most likely to be encountered.

2025-01-02 14:53 UTC, kaitlinnewson requested changes

2025-01-02 14:53 UTC, kaitlinnewson commented on episodes/05-counting-mining.md
> +Learners may encounter some inconsistent behaviour between operating systems when solving the challenge below.
Since this is referring to the next section, it would make sense to move this into that section (as an H3 under the next H2). Right now this positions it as a heading under the previous solution that it isn't related to.

2025-01-06 09:58 UTC, tobyhodges commented on episodes/05-counting-mining.md
> +Learners may encounter some inconsistent behaviour between operating systems when solving the challenge below.
Thanks for the review @kaitlinnewson. To make sure that I understand correctly: you would prefer the instructor note to appear inside the challenge block it refers to, rather than above it?

2025-02-12 15:22 UTC, kaitlinnewson approved these changes

2025-02-12 15:22 UTC, merged